# Generated by Django 3.1.3 on 2022-01-02 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vapeasy', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='voter',
            field=models.ManyToManyField(related_name='voter_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
