# Generated by Django 3.1.3 on 2022-01-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapeasy', '0008_auto_20220104_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='survey',
        ),
    ]
