# Generated by Django 3.1.3 on 2022-01-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapeasy', '0009_remove_answer_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('sort1', models.CharField(max_length=50)),
                ('sort2', models.CharField(max_length=50)),
            ],
        ),
    ]
