# Generated by Django 3.1.3 on 2022-01-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapeasy', '0010_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='answer1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='answer2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='answer3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='answer4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
