# Generated by Django 3.1.3 on 2022-05-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapeasy', '0011_auto_20220104_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='choice',
            new_name='menthol',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sort1',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sort2',
            new_name='menthol',
        ),
        migrations.AddField(
            model_name='answer',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='sweet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sweet',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
