# Generated by Django 3.1.3 on 2022-07-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapeasy', '0015_auto_20220719_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
